# git-cliff ~ default configuration file
# https://git-cliff.org/docs/configuration
#
# Lines starting with "#" are comments.
# Configuration options are organized into tables and keys.
# See documentation for more information on available options.

[changelog]
# changelog header
header = """
# What's changed
"""
# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
body = """
{% for group, commits in commits | group_by(attribute="group") %}
  ### {{ group | upper_first }}
  {% for commit in commits | unique(attribute="message") %}
    - {{ commit.message | upper_first }}\
    {% set elements = commit.scope | default(value="") | trim | split(pat="/") %}\
    {% for element in elements %}\
      {% set group = element | trim | split(pat=",") | join(sep=", ") %}\
      {% if group %} ({{ group | upper }}){% endif %}\
    {% endfor %}\
  {% endfor %}
{% endfor %}
{% if version %}\
  {% if previous %}\
    {% if previous.version %}\
      **Full Changelog:** [`{{ previous.version }}...{{ version }}`](<REPO>/compare/{{ previous.version }}...{{ version }})
    {% else %}\
      **Full Changelog:** [`{{ version }}`](<REPO>/releases/tag/{{ version }})
    {% endif %}\
  {% endif %}\
{% else %}\
  {% if previous %}\
    {% if previous.version %}\
      **Full Changelog:** [`{{ previous.version }}...HEAD`](<REPO>/compare/{{ previous.version }}...HEAD)
    {% else %}\
      **Full Changelog:** [HEAD]
    {% endif %}\
  {% else %}\
    **Full Changelog:** [HEAD]
  {% endif %}\
{% endif %}\
"""

# remove the leading and trailing whitespace from the template
trim = true
# changelog footer
footer = """

<!-- generated by git-cliff -->
"""
# postprocessors
postprocessors = [
  { pattern = '<REPO>', replace = "https://github.com/tvcsantos/v2c-any" }, # replace repository URL
]
[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = true
# filter out the commits that are not conventional
filter_unconventional = true
# process each line of a commit as an individual commit
split_commits = false
# regex for preprocessing the commit messages
commit_preprocessors = [
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))" }, # replace issue numbers
]
# regex for parsing and grouping commits
#commit_parsers = [
#  { message = "^.*: add", group = "Added" },
#  { message = "^.*: support", group = "Added" },
#  { message = "^.*: remove", group = "Removed" },
#  { message = "^.*: delete", group = "Removed" },
#  { message = "^test", group = "Fixed" },
#  { message = "^fix", group = "Fixed" },
#  { message = "^.*: fix", group = "Fixed" },
#  { message = "^.*", group = "Changed" },
#]
commit_parsers = [
  { message = "^feat", group = "‚ú® Features" },
  { message = "^fix", group = "üêõ Bug Fixes" },
  { message = "^doc", group = "üìù Documentation" },
  { message = "^perf", group = "‚ö°Ô∏è Performance" },
  { message = "^refactor", group = "‚ôªÔ∏è Refactor" },
  { message = "^style", group = "üé® Styling" },
  { message = "^test", group = "‚úÖ Testing" },
  { message = "^build", group = "ü§ñ Build" },
  { message = "^ci", group = "üîÅ CI" },
  { message = "^chore", group = "üì¶ Chores" },
  #{ message = "^chore\\(release\\): prepare for", skip = true },
  #{ message = "^chore\\(deps\\)", skip = true },
  #{ message = "^chore\\(pr\\)", skip = true },
  #{ message = "^chore\\(pull\\)", skip = true },
  #{ message = "^chore|ci", group = "Miscellaneous Tasks" },
  #{ body = ".*security", group = "Security" },
  { message = "^revert", group = "‚è™ Revert" },
]
# protect breaking changes from being skipped due to matching a skipping commit_parser
protect_breaking_commits = false
# filter out the commits that are not matched by commit parsers
filter_commits = true #false
# glob pattern for matching git tags
tag_pattern = "^v\\d+\\.\\d+\\.\\d+$"
# regex for skipping tags
skip_tags = "v0.1.0-beta.1"
# regex for ignoring tags
ignore_tags = ""
# sort the tags topologically
topo_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"
# limit the number of commits included in the changelog.
# limit_commits = 42
